"""Analyse the background track and write src/beatmap.js for the animation.

    python3 analyze.py <input audio or video>

Produces build/bgm.wav (the audio, untouched apart from decoding) and src/beatmap.js with:
  - a constant beat grid (BPM + phase) fitted to the onsets at ~3 ms resolution,
  - detected low-band hits (kick / 808) and mid-band hits (snare, claps, percussion),
  - each mid hit's brightness (spectral centroid, 0..1) — the track has little pitched melody,
  - low / mid / high band envelopes at 60 fps for audio-reactive glow.
"""
import json
import subprocess
import sys

import imageio_ffmpeg
import librosa
import numpy as np

src = sys.argv[1]
subprocess.run([imageio_ffmpeg.get_ffmpeg_exe(), '-y', '-v', 'error', '-i', src, '-vn', '-ac', '2', '-ar', '44100',
                '-c:a', 'pcm_s16le', 'build/bgm.wav'], check=True)
y, sr = librosa.load('build/bgm.wav', sr=44100, mono=True)
dur = len(y) / sr

# ---- band onset envelopes at 128-sample hops (2.9 ms)
hop = 128
S = np.abs(librosa.stft(y, n_fft=1024, hop_length=hop))
f = librosa.fft_frequencies(sr=sr, n_fft=1024)
t = librosa.frames_to_time(np.arange(S.shape[1]), sr=sr, hop_length=hop)


def flux(lo, hi):
    B = np.log1p(100 * S[(f >= lo) & (f < hi)])
    return np.concatenate([[0], np.maximum(0, np.diff(B, axis=1)).sum(0)])


def peaks(env, pct, gap):
    thr, out = np.percentile(env, pct), []
    for i in range(1, len(env) - 1):
        if env[i] > thr and env[i] >= env[i - 1] and env[i] >= env[i + 1]:
            if not out or t[i] - out[-1][0] > gap:
                out.append((t[i], env[i]))
            elif env[i] > out[-1][1]:
                out[-1] = (t[i], env[i])
    return out


lowf, midf, hif = flux(30, 160), flux(160, 2500), flux(2500, 16000)
kicks, mids = peaks(lowf, 97, 0.12), peaks(midf, 97, 0.12)

# ---- constant grid: BPM and phase that put the most onset energy on 8th notes
env = lowf / lowf.max() + midf / midf.max() + 0.5 * hif / hif.max()
best = None
for bpm in np.arange(100, 180, 0.01):
    beat = 60 / bpm
    for ph in np.arange(0, beat, 0.002):
        idx = np.clip(np.round(np.arange(ph, t[-1], beat / 2) / (hop / sr)).astype(int), 0, len(env) - 1)
        sc = env[idx].mean()
        if best is None or sc > best[0]:
            best = (sc, bpm, ph)
_, bpm, phase = best

# ---- brightness of each mid hit
cent = librosa.feature.spectral_centroid(y=y, sr=sr, hop_length=hop)[0]
lo_c, hi_c = np.percentile(cent, 5), np.percentile(cent, 95)
bright = lambda t0: float(np.clip((np.median(cent[int(t0 * sr / hop):int((t0 + 0.08) * sr / hop)]) - lo_c) / (hi_c - lo_c), 0, 1))

# ---- 60 fps band envelopes
H = 735
S2 = np.abs(librosa.stft(y, n_fft=2048, hop_length=H))
f2 = librosa.fft_frequencies(sr=sr, n_fft=2048)


def band(lo, hi):
    e = np.sqrt((S2[(f2 >= lo) & (f2 < hi)] ** 2).mean(0))
    return np.clip(e / np.percentile(e, 99), 0, 1.2)


bm = {
    'bpm': round(float(bpm), 3), 'beat': round(60 / float(bpm), 6), 'phase': round(float(phase), 4), 'duration': round(dur, 4),
    'kicks': [round(float(k), 4) for k, _ in kicks],
    'mids': [{'t': round(float(m), 4), 'b': round(bright(m), 3)} for m, _ in mids],
    'env': {k: [round(float(x), 3) for x in band(*r)] for k, r in {'low': (30, 160), 'mid': (160, 2500), 'high': (2500, 16000)}.items()},
}
with open('src/beatmap.js', 'w') as fh:
    fh.write('// Generated by analyze.py from the background track. Do not edit by hand.\nconst BEATMAP = ' + json.dumps(bm) + ';\n')
print(f"{bm['bpm']} BPM, first beat {bm['phase']} s, {dur:.2f} s, {len(bm['kicks'])} low hits, {len(bm['mids'])} mid hits")
